language: node_js
node_js:
  - '7'
dist: trusty

before_install:  
  - sudo apt-get remove docker docker-engine
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce

script:
  - npm install
  - npm run build
  - npm test
  - npm prune --production
  - docker build -t vipercloud/web:latest -t vipercloud/web:$TRAVIS_BUILD_NUMBER .

after_success:
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker push vipercloud/web:$TRAVIS_BUILD_NUMBER
 - docker push vipercloud/web:latest
